name: JavaWebApp CI/CD Workflow

on:
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest
    env:
      SONARQUBEURL: http://35.154.32.179:9000/
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
    - name: Setup Java 
      uses: actions/setup-java@v5
      with:
        distribution: 'temurin'
        java-version: '11'
        cache: 'maven'
    - name: Print Java Version
      run: java -version
    - name: Print Maven Version
      run: mvn --version      
    - name: Maven Clean Package
      run:  mvn clean package
    - name: Sonar Scan
      run: mvn clean verify sonar:sonar -Dsonar.host.url=$SONARQUBEURL -Dsonar.token=${{ secrets.SONARQUBETOKEN }}
    - name: Copy Application War via SSH to Tomcat Sever
      uses: nogsantos/scp-deploy@master
      with:
        host: ${{ vars.TOMCAT_VM_IP }}
        user: ${{ secrets.TOMCAT_VM_USERNAME }}
        key: ${{ secrets.TOMCAT_VM_SSH_KEY }}
        port: 22
        src: "target/java-web-app.war"
        remote: "/opt/tomcat/webapps"