name: JavaWebApp CI/CD Workflow

on:
  workflow_dispatch:
  push:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      SONARQUBEURL: http://35.154.32.179:9000/
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
    - name: Setup Java 
      uses: actions/setup-java@v5
      with:
        distribution: 'temurin'
        java-version: '11'
        cache: 'maven'
    - name: Print Java Version
      run: java -version
    - name: Print Maven Version
      run: mvn --version      
    - name: Maven Clean Package
      run:  mvn clean package
    - name: Sonar Scan
      run: mvn clean verify sonar:sonar -Dsonar.host.url=$SONARQUBEURL -Dsonar.token=${{ secrets.SONARQUBETOKEN }}
    - name: Uplodate war file
      uses: actions/upload-artifact@v4
      with:
        name: javawebappwar
        path: target/java-web-app.war

  
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Download Artifact
      uses: actions/download-artifact@v4
      with:
        name: javawebappwar
    - name:  List Contents
      run: ls -lar
    - name: Run commands on remote server via SSH
      uses: appleboy/ssh-action@v1.0.3 # Use the latest version from the marketplace
      with:
        host: ${{ vars.TOMCAT_VM_IP }}
        username: ${{ secrets.TOMCAT_VM_USERNAME }}
        key: ${{ secrets.TOMCAT_VM_SSH_KEY }}
        script: |
            sudo systemctl stop tomcat
            rm /opt/tomcat/webapps/java-web-app.war || true
            sleep 30
            sudo systemctl start tomcat
    - name: Copy Application War via SSH to Tomcat Sever
      uses: appleboy/scp-action@v1
      with:
        host: ${{ vars.TOMCAT_VM_IP }}
        username: ${{ secrets.TOMCAT_VM_USERNAME }}
        key: ${{ secrets.TOMCAT_VM_SSH_KEY }}
        port: 22
        source: "java-web-app.war"
        target: "/opt/tomcat/webapps"